stages:
  - build
  - deploy

build_stage:
  stage: build
  image: node:lts
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm install
    - npm run build:stage
  only:
    - test
  artifacts:
    paths:
      - dist/

deploy_stage:
  stage: deploy
  image: node:lts
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST -p 22 > ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "rm -rf /local/testhtml/* && cp $CI_PROJECT_DIR/dist/* /local/testhtml"
  dependencies:
    - build_stage
  only:
    - test