stages:
  - build
  - deploy

build_stage:
  stage: build
  image: node:lts
  script:
    - git clone -b test https://gitlab.enu.kz/enu/mobilefrontend.git && cd mobilefrontend
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm install
    - npm run build:stage
  only:
    - test

deploy_stage:
  stage: deploy
  script:
    - ssh root@smart.enu.kz "rm -rf /local/testhtml/*"
    - scp -r dist/* root@smart.enu.kz:/local/testhtml
  only:
    - test
