stages:
  - build
  - deploy

before_script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H smart.enu.kz >> ~/.ssh/known_hosts

build_stage:
  stage: build
  image: node:lts
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm install
    - npm run build:stage
  only:
    - test
  artifacts:
    paths:
      - dist/

deploy_stage:
  stage: deploy
  image: node:lts
  script:
    - ssh root@smart.enu.kz "sudo rm -rf /local/testhtml/*"
    - scp -r dist/* root@smart.enu.kz:/local/testhtml
  dependencies:
    - build_stage
  only:
    - test