stages:
  - build
  - deploy

before_script:
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H smart.enu.kz >> ~/.ssh/known_hosts

build_stage:
  stage: build
  image: node:lts
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm install
    - npm run build:stage
  only:
    - test
  artifacts:
    paths:
      - dist/

deploy_stage:
  stage: deploy
  image: node:lts
  script:
    - ssh $SSH_USER@$SSH_HOST "rm -rf /local/testhtml/* && cp $CI_PROJECT_DIR/dist/* /local/testhtml"
  dependencies:
    - build_stage
  only:
    - test