stages:
  - install
  - build
  - deploy

variables:
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
  MASTER_ARTIFACT_PATH: "dist_prod/"
  TEST_ARTIFACT_PATH: "dist_test/"
  NODE_OPTIONS: "--max-old-space-size=4096"

cache:
  paths:
    - node_modules/

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
  - wget -qO- https://get.docker.com/gpg | apt-key add -
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - touch ~/.ssh/config
  - touch ~/.ssh/known_hosts
  - chmod -R 400 ~/.ssh
  - ssh-keyscan -H smart.enu.kz >> ~/.ssh/known_hosts
  - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

install_stage:
  stage: install
  image: node:18
  script:
    - npm ci
  only:
    - master
    - test
  tags:
    - front
  artifacts:
    paths:
      - node_modules/

build_stage:
  stage: build
  image: node:18
  script:
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then
      npm run build;
      mv dist dist_prod;
      else
      npm run build:stage;
      mv dist dist_test;
      fi
  dependencies:
    - install_stage
  only:
    - master
    - test
  tags:
    - front
  artifacts:
    paths:
      - dist_prod/
      - dist_test/

deploy_stage:
  stage: deploy
  image: node:lts
  script:
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then
      ssh root@smart.enu.kz "sudo rm -rf /local/prohtml/*";
      scp -r dist_prod/* root@smart.enu.kz:/local/prohtml;
      elif [ "$CI_COMMIT_BRANCH" == "test" ]; then
      ssh root@smart.enu.kz "sudo rm -rf /local/testhtml/*";
      scp -r dist_test/* root@smart.enu.kz:/local/testhtml;
      fi
  dependencies:
    - build_stage
  only:
    - master
    - test
  tags:
    - front
