stages:
  - build
  - deploy

variables:
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
  TG_ACCESS_TOKEN: 6776695616:AAEiwTHzfZPwdOiJnnBFPLfP2DzlkmrT8fA

before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
    - wget -qO- https://get.docker.com/gpg | apt-key add -
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh
    - ssh-keyscan -H smart.enu.kz >> ~/.ssh/known_hosts
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build_stage:
  stage: build
  image: node:lts
  script:
    - |
      curl --request POST --url "https://api.telegram.org/bot$TG_ACCESS_TOKEN/sendMessage" --header "Content-Type: application/json" --data "{\"chat_id\": \"-1002040225063\",\"text\": \"Building  [${CI_PROJECT_NAME}] for environment: [${TARGET}] from branch: [${CI_COMMIT_BRANCH}] 🚀\",\"disable_notification\": true}"
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm install
    - npm run build:stage
  only:
    - test
  artifacts:
    paths:
      - dist/

deploy_stage:
  stage: deploy
  image: node:lts
  script:
    - ssh root@smart.enu.kz "sudo rm -rf /local/testhtml/*"
    - scp -r dist/* root@smart.enu.kz:/local/testhtml
  dependencies:
    - build_stage
  only:
    - test